rem echo off
git init
git add Inpc1/App.xaml
git add Inpc1/App.xaml.cs
git add Inpc1/ViewModel.cs
git add Inpc1/Converters/ConverterBase.cs
git add Inpc1/Converters/MyValueConverter.cs
git add Inpc1/App.config
git add Inpc1/MainWindow.xaml
git add Inpc1/MainWindow.xaml.cs
git add Inpc1/Properties/AssemblyInfo.cs
git add Inpc1/app.config
git add Inpc1/Properties/Settings.settings
git add Inpc1/Properties/Resources.Designer.cs
git add Inpc1/Properties/Resources.resx
git add Inpc1/Properties/Settings.Designer.cs
git add Inpc1/Inpc1.csproj
git add Inpc1.sln
git add .gitignore
